//
// Created by Kamil Bonkowski on 25/05/2021.
//

#ifndef ALGORITHMS_TIME_ANALYSIS_GENERATOR_H
#define ALGORITHMS_TIME_ANALYSIS_GENERATOR_H


class Generator {

};


#endif //ALGORITHMS_TIME_ANALYSIS_GENERATOR_H
