//
// Created by Kamil Bonkowski on 25/05/2021.
//

#ifndef ALGORITHMS_TIME_ANALYSIS_REPRESENTATION_H
#define ALGORITHMS_TIME_ANALYSIS_REPRESENTATION_H


class Representation {

};


#endif //ALGORITHMS_TIME_ANALYSIS_REPRESENTATION_H
